### ISSUE TITLE
Cannot "stream" output to Ruby's stdout/stderr

### ISSUE THREAD

**Issue by jleeothon** [taccon/eksek#16]
It would be desirable that `eksek` also have some mode where it can run commands like `system()` i.e. so that the stdout/stderr are interwoven into Ruby's stdout and stderr.

Maybe this can be accomplished with the `:out` and `:in` options.

(Top of my head, pseudo-code)

```ruby
if wants_output_printed
  Open3.popen3(mycommand, out: STDOUT, err: STDERR)
end
```

Bonus: maybe we can use some IO-like object such that the output is both piped to the current process' stdout/err _and also_ into a string object.

**Comment by tacconthommy** [comment]
This would mean we would route the output directly to STDOUT/STDIN, in case this option is active, right? Would we still be able to (additionally?) get the output into the EksekResult?

**Comment by jleeothon** [comment]
DONE #24
