### ISSUE TITLE
Accept a Logger object

### ISSUE THREAD

**Issue by jleeothon** [taccon/eksek#17]
It is arguably desirable that `eksek` could use a `Logger` object.

For example, my project has a specific message format and logic to determine the log level, and I'd like to inject this logger into the `Eksekuter`.

- [ ] Update `README.md`.
- [ ] Accept an overridable logger instance per Eksekuter.
- [ ] Allow the `Eksekuter` to run several commands i.e. don't keep state.
- [ ] Move the `Eksekuter` arguments to `Eksekuter#run`.
- [ ] Find a cuter name for `Eksekuter#run`.

**Comment by tacconthommy** [comment]
There seems to be the standard [`Logger` class](https://ruby-doc.org/stdlib-2.5.0/libdoc/logger/rdoc/Logger.html) that we could use for that. Either it could be injected or created – does that make sense?

**Comment by jleeothon** [comment]
Updated the description to reflect our last chat
